### ISSUE TITLE
Do I need to split 'test.json' into train, dev and test sets? how many for each type? Thank you

### ISSUE THREAD

**Issue by nguyenchiminh99** [freesunshine0316/neural-graph-to-seq-mp#23]
Do I need to split 'test.json' into train, dev and test sets? how many for each type? Thank you

**Comment by nguyenchiminh99** [comment]
> Do I need to split 'test.json' into train, dev and test sets? how many for each type? Thank you
Because I have seen an error when i run
Traceback (most recent call last):
  File "src_g2s/G2S_trainer.py", line 385, in <module>
    tf.compat.v1.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Anaconda3\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "D:\Anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "src_g2s/G2S_trainer.py", line 107, in main
    devset, tst_node, tst_in_neigh, tst_out_neigh, tst_sent = G2S_data_stream.read_amr_file(FLAGS.test_path)
  File "D:\XLDLL_DoanCuoiKy\neural-graph-to-seq-mp-master\src_g2s\G2S_data_stream.py", line 28, in read_amr_file
    with open(inpath, "rU") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/dev.json'
